### ISSUE TITLE
Low-friction artist pipeline

### ISSUE THREAD

**Issue by ViMaSter** [Studio-Lovelies/GG-JointJustice-Unity#399] opened 2023-10-12 01:15 UTC
## Description
[Writers can already test their scripts without using the Unity editor](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/wiki/Scripting-Basics-using-Inky#overview), let's do the same for artists.

## Acceptance Criteria

This story will be finished when
- pressing a specific combination of keys in development builds launches an artist test scene
  - runs a dialogue script, with three layers of sprites
    - layer A in the background
    - layer B in the middle
    - layer C in the foreground
  - after launching the scene, a file explorer window opens a directory containing a file for each layer
  - the scene is reloaded if any of these three files changes
- the exact combination of keys isn't defined yet; feel free to discuss (or whoever implements can just pick one)
- documentation for it is added to [the GitHub Wiki](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/wiki/Scripting-Basics-using-Inky)

**Comment by notexplosive** [comment] 2024-02-04 00:56
Is this a dupe of https://github.com/Studio-Lovelies/GG-JointJustice-Unity/issues/224?

**Closed as completed** 2024-02-04 02:28 UTC
Labels: documentation, good first issue, nice to have, helps other team, art
